### ISSUE TITLE
cybr platforms list does not work properly on PVWA version 12.6

### ISSUE THREAD

**Issue by strick-j** [infamousjoeg/cybr-cli#172]
**Description**
When attempting to use "cybr cli list" a status code 500 error is returned. 

**Reproduce behavior**
1. Authenticate: "cybr logon -u $username -b $baseurl -a $authtype"
2. List Platforms: "cybr platforms list" or "cybr platforms list -a"
3. See error

**Expected behavior**
Expect to see a list of inactive and active platforms. If the -a flag is used then I expect to see only active platforms.

**Screenshots**
![image](https://user-images.githubusercontent.com/16992045/201181290-0df78e50-75e1-4634-b02f-1f527df4597a.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.6

**CyberArk Version :**
 - PVWA: 12.6.0.40

**Comment by infamousjoeg** [comment]
@strick-j,

My tests are successful using cybr-cli v0.1.12-beta with the following CyberArk version:

```json
{
    "ExternalVersion": "12.6.0",
    "InternalVersion": "12.6.0.40",
    "ServerName": "Vault"
}
```

Can you run `cybr version` and let me know what is returned? I suspect you may be on an older version than latest.

**Comment by strick-j** [comment]
Please disregard. There was an issue with platforms in my environment as described here: https://cyberark-customers.force.com/s/article/pCloud-Get-Platforms-API-returns-CAWS00001E-The-given-key-was-not-present-in-the-dictionary
