### ISSUE TITLE
cybr --verbose flag

### ISSUE THREAD

**Issue by AndrewCopeland** [infamousjoeg/cybr-cli#37]
**Is your feature request related to a problem? Please describe.**
I would like to understand what HTTP calls is being sent to the target systems.

**Describe the solution you'd like**
`cybr <any command> --verbose`

**Comment by infamousjoeg** [comment]
We can assign these as a persistent flag on [cmd/root.go]() and they'll be available for every command: [https://github.com/spf13/cobra#persistent-flags]()
