### ISSUE TITLE
cybr accounts get?

### ISSUE THREAD

**Issue by adam0306** [infamousjoeg/cybr-cli#65]
**Is your feature request related to a problem? Please describe.**
Feature Request

**Describe the solution you'd like**
Add the ability to search for accounts to retrieve the Account ID to interact with accounts.

**Comment by AndrewCopeland** [comment]
How is this request different then the following implementation:
```bash
$ cybr account list -s test-ssh-key
{
    "value": [
        {
            "categoryModificationTime": 1611865949,
            "id": "110_15",
            "name": "Operating System-UnixSSHKeys-10.0.0.1-test-ssh-key",
            "address": "10.0.0.1",
            "userName": "test-ssh-key",
            "platformId": "UnixSSHKeys",
            "safeName": "CLI_ACCOUNTS_TEST",
            "secretType": "key",
            "platformAccountProperties": {},
            "secretManagement": {
                "automaticManagementEnabled": true,
                "status": "failure",
                "lastModifiedTime": 1611257354
            },
            "createdTime": 1611257354
        }
    ],
    "count": 1
}
```

The ID should be easily parsable from the returned json object.

**Comment by adam0306** [comment]
It isn't. A case of user not familiar enough with the tool. Closing.

**Comment by AndrewCopeland** [comment]
You can find documentation on the `cybr account` command here:
https://github.com/infamousjoeg/cybr-cli/blob/main/docs/cybr_accounts.md

Thanks for using the `cybr-cli`!
