### ISSUE TITLE
`cybr ccp retrieve-account`

### ISSUE THREAD

**Issue by AndrewCopeland** [infamousjoeg/cybr-cli#67]
**Is your feature request related to a problem? Please describe.**
Currently I cannot use the `cybr-cli` with CCP.

**Describe the solution you'd like**
I would like the ability to easily retrieve credentials from the CCP via the following command:
```bash
cybr ccp retrieve-account --url https://url-to-ccp.company.local --app-id AppID --query "Query=Safe=Billing;Object=MonthlyBilling" --field password
```

**Addition Notes**
Extra flags may be required because:
- CCP supports client certificate authentication 
- CCP supports OS Users authentication (for windows).

**Comment by infamousjoeg** [comment]
1. We should support more than just `--query`.  I think `--query` is good for situations where the entire query is stored in an app, to prevent code changes to work with our CLI, but I also think we should provide separate flags for each query key, as well.  `--safe`, `--object`, `--username`, etc.
2. `--field` should support multiple comma-delimited values. `Password` is already a default returned value and doesn't need to be provided. Example: `--field Address,UserName` would return `password, address, username`.

**Comment by AndrewCopeland** [comment]
Sounds great! I am also thinking about have a --certificate flag for providing a certificate for authn
