### ISSUE TITLE
consider pre-defined ACLs for common user types

### ISSUE THREAD

**Issue by jodyhuntatx** [infamousjoeg/cybr-cli#87]
As an impatient workflow developer
I don't want to look at documentation or PVWA to remember what permissions to give common user types on a safe.
Having pre-defined ACLs for users like Admins, Auditors, LOB users, etc. would ensure consistency and less chance of overprivilege.

**Comment by infamousjoeg** [comment]
@jodyhuntatx This is currently being worked on in the `fix-87-predefined-safe-acl` branch. Were there any particular roles you were looking to have pre-defined or are you just hoping for commonly used recommendations?

**Comment by infamousjoeg** [comment]
Here is where roles are being defined: https://github.com/infamousjoeg/cybr-cli/blob/fix-87-predefined-safe-acl/pkg/cybr/api/roles.go
