### ISSUE TITLE
"cybr conjur list" should return everything by default

### ISSUE THREAD

**Issue by jodyhuntatx** [infamousjoeg/cybr-cli#90]
**Is your feature request related to a problem? Please describe.**
the conjur-cli container returns everything. consistency with that would seem a good thing

**Describe the solution you'd like**
cybr conjur list - returns everything visible to the logged-in identity

**Comment by infamousjoeg** [comment]
@jodyhuntatx Have you tested that PR #94 meets your requested enhancement?  If not, could you and let me know here?

Thanks!
